### PR TITLE
logo appears centered again

### PR DESCRIPTION
**Pull request by mdb**
fixes issue #33

### CODE REVIEW

**Comment by mdb** [comment]
@iamjarvo @justincampbell Please let me know what you think of this -- I believe this is safe to merge and will address the mis-aligned Philly.rb logo which is currently in production.

**Comment by justincampbell** [comment]
:+1:

Merging to deploy and see what happens, Hard to reproduce with Chrome Inspector because of the `@include`.

**Comment by justincampbell** [comment]
Looks good!

**Comment by mdb** [comment]
Thanks!

**Pull request merged**
